### ISSUE TITLE
Book?

### ISSUE THREAD

**Issue by jonnjonzzn** [WebucatorTraining/lahman-baseball-mysql#1]
There's mention of a book in README.  I'd be interested.  Can you share anymore information about it?

**Comment by ndunn219** [comment]
Thanks for asking! I just added a link to the book (https://www.amazon.com/Python-3-8-Nat-Dunn/dp/1951959027). The book is on Python. It uses the Lahman database for some of the examples, but doesn't get deep into the database itself.
